name: Node CI

on: [push]

jobs:
  test:
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [10]
        os: [ubuntu-18.04]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          version: ${{ matrix.node_version }}
      - run: npm run setup-npmrc
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
      - run: npm install
      - name: npm build and test
        run: |
          npm run build --if-present
          npm test
        env:
          CI: true
